### ISSUE TITLE
Fix Tier System

### ISSUE THREAD

**Issue by agnor99** [bernie-g/Techarium#1]
In Singleplayer:
All tiers get displayed in the GUI of the botarium as Tier 5 if the machine was placed without logging out. After reentering the world all machines are tier 1. 
In Multiplayer:
You can't open the botarium at all. The Server tries to load the widget class, but can't find it, because it has the @OnlyIn(Dist.Client) annotation

**Comment by agnor99** [comment]
The same behaviour from Singleplayer also applies to multiplayer.

**Comment by bernie-g** [comment]
Yeah I'm aware, it's on the todo list.
