### ISSUE TITLE
Magnetic Coils don't hold NBT correctly.

### ISSUE THREAD

**Issue by CIbben** [bernie-g/Techarium#75]
https://user-images.githubusercontent.com/84931476/127060313-5c23f0ca-0e9e-46b1-b178-dbef4df98bc3.mp4

When copying a Magnetic Coil with NBT value it keeps the coil in its inventory, but it doesn't render and it doesn't work behind a Grav Magnet.

**Comment by Lazzzzz** [comment]
Mmmm when disconnect / reconnect it's working again, maybe a sync server client problem, gonna look into that
